---
title: "Women GMHS 2017"
author: "Ama Korantema Owusu-Darko"
date: "10/10/2020"
output: html_notebook
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

```

## Age at First Birth /Birth before age 19

The goal of this research is to identify factors the are associated with a women giving birth to a child before age 19.

```{r setup  data, echo=FALSE}
knitr::opts_chunk$set(include = FALSE, warning = FALSE)

library(haven)
library(broom)
library(janitor)
library(ggforce)
library(table1)
library(vcd)
library(mosaic)
library(epitools)
library(epitools)
library(ggmap)
library(gghighlight)
library(ggformula)
library(ggsci)
library(ggridges)
library(ggrepel)
library(tidycomm)

library(scales)
library(ggpubr)
library(magrittr)
library(tidylog)
library(tidyverse)
```

```{r load data, include=FALSE, paged.print=TRUE,echo=FALSE}
women <- read_dta("idhs.dta")


```

```{r read data, include=FALSE, paged.print=TRUE,echo=FALSE}
fp2<-women%>%
  filter(ageat1stbirth<99,resident<2,agefrstmar<99,lit2<98)%>%
  select(-starts_with("age5"))%>%
  mutate(across(c(urban,resident,marstat,currwork, wkmaternity,wkearnsmore,wealthq,lit2,educlvl,37:50), as_factor))%>%
  mutate(across(c(urban,resident,marstat,currwork, wkmaternity,wkearnsmore,wealthq,lit2,educlvl,37:50), droplevels))

fp2$early_mar=cut(fp2$agefrstmar,breaks=c(-Inf,19,Inf), labels=c("married before 19","married after 19"))

fp2$early_bir=cut(fp2$ageat1stbirth,breaks=c(-Inf,19,Inf), labels=c("birth before 19","birth after 19"))

```

```{r Table1, echo=FALSE}
table1(~age+early_mar+lit2+educlvl+edyrtotal|early_bir,droplevels=T, data=fp2)
```
